-- Æwiczenia laboratoryjne: Wprowadzenie, typ SDO_GEOMETRY
SELECT * FROM USER_SDO_GEOM_METADATA;

-- 1A
INSERT INTO USER_SDO_GEOM_METADATA
    VALUES (
    'FIGURY',
    'KSZTALT',
    MDSYS.SDO_DIM_ARRAY(
    MDSYS.SDO_DIM_ELEMENT('X', 0, 20, 0.01),
    MDSYS.SDO_DIM_ELEMENT('Y', 0, 20, 0.01) ),
    NULL 
);

-- 1B
SELECT SDO_TUNE.ESTIMATE_RTREE_INDEX_SIZE(3000000, 8192, 10, 2, 0)
FROM dual;

-- 1C
CREATE INDEX FIGURY_IDX
ON FIGURY(KSZTALT)
INDEXTYPE IS MDSYS.SPATIAL_INDEX_V2;

-- 1D
SELECT id
FROM figury
WHERE SDO_FILTER(KSZTALT, SDO_GEOMETRY(2001,null,
 SDO_POINT_TYPE(3,3,null),
 null,null)) = 'TRUE';
 
-- 1E
SELECT id
FROM figury
WHERE SDO_RELATE(
ksztalt, 
SDO_GEOMETRY(
2001,null,SDO_POINT_TYPE(3,3,null),null,null), 
'mask=ANYINTERACT') = 'TRUE';
 
